version: '3.4'

services:
  usermanagement.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44301
      - DB_CONNECTION=Server=server-mssql;database=UserManagement;user=test;password=test;
    ports:
      - "10001:80"
      - "44201:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  productmanagement.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44302
      - DB_CONNECTION=Server=server-mssql;database=ProductManagement;user=test;password=test;
    ports:
      - "10002:80"
      - "44202:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
